# This file was *autogenerated* from the file rank.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_105 = Integer(105); _sage_const_28 = Integer(28); _sage_const_23 = Integer(23); _sage_const_21 = Integer(21); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_66 = Integer(66); _sage_const_42 = Integer(42); _sage_const_43 = Integer(43); _sage_const_44 = Integer(44); _sage_const_46 = Integer(46); _sage_const_49 = Integer(49); _sage_const_54 = Integer(54); _sage_const_82 = Integer(82); _sage_const_69 = Integer(69); _sage_const_58 = Integer(58); _sage_const_40 = Integer(40); _sage_const_13 = Integer(13); _sage_const_118 = Integer(118); _sage_const_16 = Integer(16); _sage_const_59 = Integer(59); _sage_const_14 = Integer(14); _sage_const_57 = Integer(57); _sage_const_30 = Integer(30); _sage_const_19 = Integer(19); _sage_const_32 = Integer(32); _sage_const_35 = Integer(35); _sage_const_34 = Integer(34); _sage_const_50 = Integer(50); _sage_const_109 = Integer(109); _sage_const_99 = Integer(99); _sage_const_98 = Integer(98); _sage_const_72 = Integer(72); _sage_const_91 = Integer(91); _sage_const_103 = Integer(103); _sage_const_96 = Integer(96); _sage_const_94 = Integer(94)
sage.misc.preparser.load(sage.misc.preparser.base64.b64decode("bWF0cml4XzNjLnB5"),globals(),False)

def matrix_gf2_rank(matrix):
  n_rows = len(matrix)
  n_columns = len(matrix[_sage_const_0 ])
  MS = MatrixSpace(GF(_sage_const_2 ), n_rows, n_columns)
  matrix_gf2 = MS(matrix)
  return matrix_gf2.rank()

matrix = zip(*matrix_3c)
full_rank = matrix_gf2_rank(matrix)
print 'Rank of the full matrix: ' + repr(full_rank)

cells_to_move = []

# core, north pole
cells_to_move += [_sage_const_0 ]

# first layer, 10 cells. Changes 32 orbits
cells_to_move += [_sage_const_28 , _sage_const_35 , _sage_const_42 , _sage_const_46 , _sage_const_57 , _sage_const_66 , _sage_const_72 , _sage_const_94 , _sage_const_96 , _sage_const_98 , _sage_const_105 , _sage_const_109 ]

# second layer, 20 cells. Changes 24 orbits
cells_to_move += [_sage_const_8 , _sage_const_9 , _sage_const_13 , _sage_const_14 , _sage_const_16 , _sage_const_19 , _sage_const_21 , _sage_const_23 , _sage_const_25 , _sage_const_32 , _sage_const_43 , _sage_const_44 , _sage_const_58 , _sage_const_59 , _sage_const_69 , _sage_const_82 , _sage_const_91 , _sage_const_99 , _sage_const_103 , _sage_const_118 ]

# third layer, 12 cells. Changes 32 orbits
# cells_to_move += [27, 40, 49, 50, 54, 55, 80, 86, 89, 93, 104, 117]
# subset of third layer
cells_to_move += [_sage_const_27 , _sage_const_40 , _sage_const_49 , _sage_const_50 , _sage_const_54 ,]

# fourth layer, equator, 30 cells. Changes 0 orbit
# cells_to_move += [1, 3, 4, 5, 6, 7, 24, 26, 30, 31, 34, 36, 37, 38, 39, 41, 53, 61, 63, 65, 70, 73, 76, 77, 78, 83, 88, 101, 102, 111]
# subset of equators
cells_to_move += [_sage_const_1 , _sage_const_3 , _sage_const_4 , _sage_const_24 , _sage_const_30 , _sage_const_34 ]

# south of equator
# cells_to_move += [29, 45, 47, 52, 68, 71, 84, 92, 100, 113, 114, 115]

# second layer south of equator
# cells_to_move += [10, 11, 12, 15, 17, 18, 20, 22, 33, 48, 51, 56, 60, 62, 87, 95, 108, 110, 112, 116]

# next to south pole
# cells_to_move += [64, 67, 74, 75, 79, 81, 85, 90, 97, 106, 107, 119]

# south pole
# cells_to_move += [2]

print 'Selecting ' + repr(len(cells_to_move)) + ' moves'
matrix_selected = [matrix[i] for i in cells_to_move]
selected_rank = matrix_gf2_rank(matrix_selected)

print 'Rank of the selected matrix: ' + repr(selected_rank)

if selected_rank == full_rank and len(cells_to_move) == full_rank:
  from cell120 import *
  cell120 = Cell120()
  for cell_index in cells_to_move:
    print cell_index, cell120.cells[cell_index].value
else:
  pass
